version: '3.8'
services:
  db:
    image: postgres:35
    container_name: :organize-simple-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: organize-simple
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db_data:
    name: organize-simple-data
